.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-status - Show worktree runtime status


.SH SYNOPSIS
\fBwts status [worktree] [flags]\fP


.SH DESCRIPTION
Show running/active status for discovered worktrees and the currently associated process profile.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status

.PP
\fB--json\fP[=false]
	output JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts status
  wts status repo-main
  wts status --json
.EE


.SH SEE ALSO
\fBwts(1)\fP
