.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-stop - Stop worktree process(es)


.SH SYNOPSIS
\fBwts stop [worktree] [flags]\fP


.SH DESCRIPTION
Stop worktree process(es)


.SH OPTIONS
\fB--all\fP[=false]
	stop all worktrees

.PP
\fB--group\fP=""
	stop active worktree in group

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stop


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
