.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-logs - Show recent tmux pane output for a worktree


.SH SYNOPSIS
\fBwts logs  [flags]\fP


.SH DESCRIPTION
Capture recent output lines from the tmux window for a running worktree process.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for logs

.PP
\fB--lines\fP=200
	number of log lines

.PP
\fB--process\fP=""
	process name (default: first pane)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts logs repo-main
  wts logs repo-main --process api
  wts logs ../repo-agent --lines 400
.EE


.SH SEE ALSO
\fBwts(1)\fP
