.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-next - Switch to next git worktree in list


.SH SYNOPSIS
\fBwts next [flags]\fP


.SH DESCRIPTION
Move to the next discovered worktree and hand off the selected process profile or group.


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after switching

.PP
\fB--group\fP=""
	process group name from config

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for next

.PP
\fB--process\fP=""
	process profile name (default: first process in config)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts next
  wts next --process demo-script
  wts next --group dev
  wts next --attach
.EE


.SH SEE ALSO
\fBwts(1)\fP
