.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-start - Start process in a worktree (preempts active)


.SH SYNOPSIS
\fBwts start  [flags]\fP


.SH DESCRIPTION
Start or move a process profile to a target worktree.

.PP
The currently active worktree process is stopped first, then the target process
is started in the selected worktree directory.


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after command

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for start

.PP
\fB--process\fP=""
	process profile name (default: first process in config)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts start repo-main
  wts start ../repo-agent --process demo-script
  wts start /abs/path/to/worktree --attach
.EE


.SH SEE ALSO
\fBwts(1)\fP
