.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-list - List git worktrees for this repo


.SH SYNOPSIS
\fBwts list [flags]\fP


.SH DESCRIPTION
Discover worktrees using Git and print worktree name, branch, and absolute directory.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts list
.EE


.SH SEE ALSO
\fBwts(1)\fP
