.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-group - Set or clear group override for a worktree


.SH SYNOPSIS
\fBwts group  [flags]\fP


.SH DESCRIPTION
Set or clear group override for a worktree


.SH OPTIONS
\fB--clear\fP[=false]
	clear group override

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for group

.PP
\fB--set\fP=""
	set group override


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
