.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-logs - Show recent tmux pane output for a worktree


.SH SYNOPSIS
\fBwts logs  [flags]\fP


.SH DESCRIPTION
Show recent tmux pane output for a worktree


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for logs

.PP
\fB--lines\fP=200
	number of log lines


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
