.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-version - Show wts version


.SH SYNOPSIS
\fBwts version [flags]\fP


.SH DESCRIPTION
Show wts version


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH SEE ALSO
\fBwts(1)\fP
