.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-add - Add a worktree directory assignment


.SH SYNOPSIS
\fBwts add  [flags]\fP


.SH DESCRIPTION
Add a worktree directory assignment


.SH OPTIONS
\fB--group\fP=""
	optional group override

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add

.PP
\fB--name\fP=""
	worktree alias name

.PP
\fB--process\fP=""
	process profile name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
