.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-processes - List process profiles from config


.SH SYNOPSIS
\fBwts processes [flags]\fP


.SH DESCRIPTION
List process profiles from config


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for processes


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
