.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-start - Start workspace process and make it active for its group


.SH SYNOPSIS
\fBwts start  [flags]\fP


.SH DESCRIPTION
Start a workspace process using the configured command in its directory.

.PP
Like switch, start preempts the currently active workspace in the same group.
If target is already running, it is reused unless you run restart.


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after starting

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for start


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml (legacy: .worktreeswitch.yaml/.workswitch.yaml)


.SH EXAMPLE
.EX
  wts start web-main
  wts start web-agent-a --attach
.EE


.SH SEE ALSO
\fBwts(1)\fP
