.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-restart - Restart process for a worktree


.SH SYNOPSIS
\fBwts restart  [flags]\fP


.SH DESCRIPTION
Restart process for a worktree


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after command

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for restart


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
