.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-prev - Switch to previous git worktree in list


.SH SYNOPSIS
\fBwts prev [flags]\fP


.SH DESCRIPTION
Move to the previous discovered worktree and hand off the selected process profile.


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after switching

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for prev

.PP
\fB--process\fP=""
	process profile name (default: first process in config)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts prev
  wts prev --process api
  wts prev --attach
.EE


.SH SEE ALSO
\fBwts(1)\fP
