.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-tui - Open interactive Bubble Tea TUI


.SH SYNOPSIS
\fBwts tui [flags]\fP


.SH DESCRIPTION
Open the interactive TUI for worktree/process handoff.

.PP
The TUI lets you move selection across discovered worktrees, choose process
profiles, and switch/restart/stop quickly.

.PP
Shortcuts:
  n/down   next worktree
  p/up     previous worktree
  [ / ]    previous/next process profile
  s/enter  switch
  r        restart
  x        stop
  ?        toggle shortcut help
  q        quit

.PP
Exiting TUI does not stop running worktree processes.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tui


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts tui
.EE


.SH SEE ALSO
\fBwts(1)\fP
