.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-pick - Pick a worktree and switch


.SH SYNOPSIS
\fBwts pick [flags]\fP


.SH DESCRIPTION
Pick a worktree and switch


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after switching

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pick


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
