.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-pick - Pick a git worktree and switch


.SH SYNOPSIS
\fBwts pick [flags]\fP


.SH DESCRIPTION
Open an interactive selector (fzf if installed, fallback prompt otherwise) and switch to the chosen worktree.


.SH OPTIONS
\fB--attach\fP[=false]
	attach/focus tmux after switching

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pick

.PP
\fB--process\fP=""
	process profile name (default: first process in config)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts pick
  wts pick --process demo-script
  wts pick --attach
.EE


.SH SEE ALSO
\fBwts(1)\fP
