.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-stop - Stop worktree process(es)


.SH SYNOPSIS
\fBwts stop [worktree] [flags]\fP


.SH DESCRIPTION
Stop process windows managed by wts.

.PP
With no arguments it stops the active worktree process.
With a selector it stops only that worktree.
With --all it stops all discovered worktree windows.


.SH OPTIONS
\fB--all\fP[=false]
	stop all discovered worktrees

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stop


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts stop
  wts stop repo-main
  wts stop /abs/path/to/worktree
  wts stop --all
.EE


.SH SEE ALSO
\fBwts(1)\fP
