.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-validate - Validate .wts.yaml


.SH SYNOPSIS
\fBwts validate [flags]\fP


.SH DESCRIPTION
Validate the process configuration file and print loaded process count.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for validate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml


.SH EXAMPLE
.EX
wts validate
  wts validate --config ../other/.wts.yaml
.EE


.SH SEE ALSO
\fBwts(1)\fP
