.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-assign - Assign a process profile to a worktree


.SH SYNOPSIS
\fBwts assign  [flags]\fP


.SH DESCRIPTION
Assign a process profile to a worktree


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for assign

.PP
\fB--process\fP=""
	process profile name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
