.nh
.TH "WORKSWITCH" "1" "Mar 2026" "workswitch" "workswitch Manual"

.SH NAME
wts-prev - Switch to previous worktree in list


.SH SYNOPSIS
\fBwts prev [flags]\fP


.SH DESCRIPTION
Switch to previous worktree in list


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for prev


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to .wts.yaml

.PP
\fB--state\fP=""
	path to state file (default ~/.workswitch/state.yaml)


.SH SEE ALSO
\fBwts(1)\fP
